spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saas_core
    username: saas
    password: saas
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: true
logging:
  level:
    org.flywaydb: debug